### ISSUE TITLE
Auto-documentation not covering all methods

### ISSUE THREAD

**Issue by CMRiggs** [spark1217/StockImpulse#6]
Methods exist in the source code that are not being added to the auto-documentation. Specifically price and stock methods are being skipped.

**Comment by CMRiggs** [comment]
Update:
pdoc will not automatically document any function that had a @client.command decoration. I tried using other tools like Sphinx and pydoc but couldn't get any to work. For now to get it to work I created dummy functions at the bottom of the source file that only exist so that the documentation tool picks it up. Based on this GitHub issue in the pdoc repository (https://github.com/mitmproxy/pdoc/issues/58) I don't think the issue is fixable. If someone wants to try setting up a different tool like pydoc, sphinx, or any other tool feel free. Ideally what I have now will be a temporary fix.

**Comment by sohambapat** [comment]
Not fixable at current scale.
